import React, { useEffect } from 'react';
import { useParams } from 'react-router-dom';
import '../ACT201/Short.css'; 
import Header from "../../Header";
import Footer from '../../Footer';

const IslamicBankingLongQuestionsPage = () => {
  const { code } = useParams();

  // Example array of long questions related to Islamic Banking & Finance
  const islamicBankingLongQuestions = [
    {
      question: 'Question 1: Analyze the principles of Islamic finance and their role in promoting ethical financial practices.',
      answer: 'Islamic finance principles, rooted in Shariah law, emphasize fairness, transparency, and ethical conduct. These principles prohibit interest (Riba) and encourage profit and loss sharing, asset-backed financing, and ethical investments. The principles play a crucial role in fostering ethical financial practices by aligning financial activities with social and moral values.',
    },
    {
      question: 'Question 2: Compare and contrast Islamic banking with conventional banking. Highlight the key differences and similarities in their operational models.',
      answer: 'Islamic banking and conventional banking differ fundamentally in their treatment of interest. While Islamic banking prohibits interest to ensure fairness and ethical conduct, conventional banking relies on interest-based transactions. Both models share similarities in providing financial services, but their operational structures, risk-sharing mechanisms, and approaches to ethical considerations distinguish them.',
    },
    {
      question: 'Question 3: Evaluate the role of Mudarabah and Musharakah in Islamic finance. How do these principles contribute to the Islamic banking system?',
      answer: 'Mudarabah and Musharakah are Islamic financing principles based on profit and loss sharing. Mudarabah involves one party providing funds (Rab al-Maal) and another party managing the investment (Mudarib). Musharakah involves a joint venture partnership. These principles contribute to the Islamic banking system by promoting risk-sharing, entrepreneurship, and fostering mutually beneficial partnerships between financial institutions and clients.',
    },
    {
      question: 'Question 4: Examine the challenges faced by Islamic banking globally. How can these challenges be addressed to ensure the continued growth and success of the Islamic banking industry?',
      answer: 'Islamic banking faces challenges such as regulatory variations, limited product diversity, and the need for standardized practices. Addressing these challenges requires collaborative efforts among regulators, financial institutions, and Islamic scholars. Implementing global standards, expanding product offerings, and enhancing public awareness can contribute to the sustained growth and success of the Islamic banking industry.',
    },
    {
      question: 'Question 5: Discuss the concept of Sukuk in Islamic finance. How do Sukuk instruments contribute to Islamic capital markets?',
      answer: 'Sukuk are Islamic financial instruments similar to bonds. They represent ownership in an underlying asset or project. Sukuk contribute to Islamic capital markets by providing an avenue for raising capital in compliance with Shariah principles. Investors receive a share of profits generated by the underlying asset. Sukuk play a vital role in supporting infrastructure projects and facilitating ethical investment opportunities in Islamic finance.',
    },
    // Add more long questions and detailed answers as needed
  ];

  useEffect(() => {
    console.log('IslamicBankingLongQuestionsPage rendered');
  }, []);

  return (
    <div>
      <Header />
      <div className="short-questions-container">
        <h1>Long Questions For Islamic Banking & Finance {code}</h1>
        {islamicBankingLongQuestions.map((qna, index) => (
          <div key={index} className="question-item">
            <strong>{qna.question}</strong>
            <p className="answer">{qna.answer}</p>
          </div>
        ))}
      </div>
      <Footer />
    </div>
  );
};

export default IslamicBankingLongQuestionsPage;
